name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker-practice/actions-setup-docker@master
    - name: build docker image
      run: docker build . -t libgraph
    - name: build lib inside container
      run: docker run --rm libgraph sh -c 'make lib'
